language: node_js
node_js:
  - "8.11.3"
dist: trusty
sudo: required
cache: yarn
addons:
  chrome: stable
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
install:
  - yarn
script:
  - yarn test